name: "Setup poetry dependencies"
description: "Setup Python interpreter and project dependencies."
inputs:
  python-version:  # id of input
    description: "Version of Python interpreter to setup"
    required: true
    default: "3.8"
  poetry-version:
    description: "Version of Poetry package manager to setup"
    required: true
    default: 1.1.6
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache python packages
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: cache-python-packages
      with:
        path: .venv
        key: ${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install poetry==${{ inputs.poetry-version }}
        poetry config virtualenvs.in-project true
        poetry install
